apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: php
          image: ghcr.io/sazibsust10/symfony-be:1.0.0
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
