name: Symfony CI/CD with Render Deploy Hook

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: intl, pdo_mysql, zip

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

      - name: PHP Lint
        run: |
          if [ -d src ]; then find src -name "*.php" -exec php -l {} \;; fi
          if [ -d tests ]; then find tests -name "*.php" -exec php -l {} \;; fi

      - name: Run Tests
        run: |
          if [ -f ./vendor/bin/phpunit ]; then ./vendor/bin/phpunit; else echo "No tests found"; fi

      - name: Deploy to Render via deploy hook
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
