apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  template:
    spec:
      containers:
        - name: postgres
          image: postgres:14
          env:
            - name: POSTGRES_DB
              value: symfony
            - name: POSTGRES_USER
              value: symfony
            - name: POSTGRES_PASSWORD
              value: symfony
