apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: php
          image: ghcr.io/sazibsust10/symfony-be:1.0.0
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
